package PrintingInterfaceApp.PrintingInterfacePackage;


/**
* PrintingInterfaceApp/PrintingInterfacePackage/intArrHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PrintingInterface.idl
* 26 ноября 2017 г. 19:05:24 MSK
*/

public final class intArrHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public intArrHolder ()
  {
  }

  public intArrHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PrintingInterfaceApp.PrintingInterfacePackage.intArrHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PrintingInterfaceApp.PrintingInterfacePackage.intArrHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PrintingInterfaceApp.PrintingInterfacePackage.intArrHelper.type ();
  }

}
