package GameInterfaceApp;


/**
* GameInterfaceApp/GameInterfaceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterface.idl
* 26 ноября 2017 г. 21:55:40 MSK
*/

public interface GameInterfaceOperations 
{
  int[] turn (int fieldN, int fieldW, boolean current_player);
  String concede (boolean current_player);
  String getResult ();
  void startGame ();
  boolean isGameEnded ();
} // interface GameInterfaceOperations
