package GameInterfaceApp;

/**
* GameInterfaceApp/GameInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterface.idl
* 26 ноября 2017 г. 21:55:40 MSK
*/

public final class GameInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public GameInterfaceApp.GameInterface value = null;

  public GameInterfaceHolder ()
  {
  }

  public GameInterfaceHolder (GameInterfaceApp.GameInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameInterfaceApp.GameInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameInterfaceApp.GameInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameInterfaceApp.GameInterfaceHelper.type ();
  }

}
