package GameInterfaceApp;


/**
* GameInterfaceApp/GameInterfaceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterface.idl
* 26 ноября 2017 г. 21:55:40 MSK
*/

abstract public class GameInterfaceHelper
{
  private static String  _id = "IDL:GameInterfaceApp/GameInterface:1.0";

  public static void insert (org.omg.CORBA.Any a, GameInterfaceApp.GameInterface that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static GameInterfaceApp.GameInterface extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (GameInterfaceApp.GameInterfaceHelper.id (), "GameInterface");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static GameInterfaceApp.GameInterface read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameInterfaceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, GameInterfaceApp.GameInterface value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static GameInterfaceApp.GameInterface narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameInterfaceApp.GameInterface)
      return (GameInterfaceApp.GameInterface)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameInterfaceApp._GameInterfaceStub stub = new GameInterfaceApp._GameInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static GameInterfaceApp.GameInterface unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof GameInterfaceApp.GameInterface)
      return (GameInterfaceApp.GameInterface)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      GameInterfaceApp._GameInterfaceStub stub = new GameInterfaceApp._GameInterfaceStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
