package GameInterfaceApp;


/**
* GameInterfaceApp/GameInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterface.idl
* 26 ноября 2017 г. 21:55:40 MSK
*/

public interface GameInterface extends GameInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameInterface
