package PrintingInterfaceApp;


/**
* PrintingInterfaceApp/PrintingInterfacePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PrintingInterface.idl
* 26 ноября 2017 г. 19:05:24 MSK
*/

public abstract class PrintingInterfacePOA extends org.omg.PortableServer.Servant
 implements PrintingInterfaceApp.PrintingInterfaceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("printGamingField", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PrintingInterfaceApp/PrintingInterface/printGamingField
       {
         int status[] = PrintingInterfaceApp.PrintingInterfacePackage.intArrHelper.read (in);
         this.printGamingField (status);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PrintingInterfaceApp/PrintingInterface:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PrintingInterface _this() 
  {
    return PrintingInterfaceHelper.narrow(
    super._this_object());
  }

  public PrintingInterface _this(org.omg.CORBA.ORB orb) 
  {
    return PrintingInterfaceHelper.narrow(
    super._this_object(orb));
  }


} // class PrintingInterfacePOA
