package PrintingInterfaceApp;


/**
* PrintingInterfaceApp/PrintingInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PrintingInterface.idl
* 26 ноября 2017 г. 19:05:24 MSK
*/

public interface PrintingInterface extends PrintingInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PrintingInterface
