package PrintingInterfaceApp;

/**
* PrintingInterfaceApp/PrintingInterfaceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PrintingInterface.idl
* 26 ноября 2017 г. 19:05:24 MSK
*/

public final class PrintingInterfaceHolder implements org.omg.CORBA.portable.Streamable
{
  public PrintingInterfaceApp.PrintingInterface value = null;

  public PrintingInterfaceHolder ()
  {
  }

  public PrintingInterfaceHolder (PrintingInterfaceApp.PrintingInterface initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PrintingInterfaceApp.PrintingInterfaceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PrintingInterfaceApp.PrintingInterfaceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PrintingInterfaceApp.PrintingInterfaceHelper.type ();
  }

}
