package GameInterfaceApp.GameInterfacePackage;


/**
* GameInterfaceApp/GameInterfacePackage/intArrHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameInterface.idl
* 26 ноября 2017 г. 21:55:40 MSK
*/

public final class intArrHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public intArrHolder ()
  {
  }

  public intArrHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameInterfaceApp.GameInterfacePackage.intArrHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameInterfaceApp.GameInterfacePackage.intArrHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameInterfaceApp.GameInterfacePackage.intArrHelper.type ();
  }

}
